# Generated by Django 5.1.4 on 2025-01-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=100)),
            ],
        ),
    ]
