# Generated by Django 5.1.5 on 2025-01-31 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_rename_cidade_cadastr_cidade_e_estado_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cadastr',
            new_name='Cadastro',
        ),
    ]
