# Generated by Django 5.1.4 on 2025-02-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_pessoais',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
