# Generated by Django 5.1.4 on 2025-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_dados_pessoais_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_pessoais',
            name='descricao',
            field=models.CharField(max_length=100),
        ),
    ]
