# Generated by Django 5.1.4 on 2024-12-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('Cursos_fk', models.CharField(max_length=100)),
            ],
        ),
    ]
