# Generated by Django 5.1.4 on 2025-01-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aulas',
            name='cursos',
        ),
    ]
