# Generated by Django 5.1.4 on 2025-02-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0004_curso_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
