# Generated by Django 5.1.4 on 2025-02-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0006_aulas_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='material_escrito',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
