# Generated by Django 5.1.4 on 2025-02-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0008_alter_curso_material_escrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='material_escrito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
