# Generated by Django 5.1.4 on 2025-02-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0009_alter_curso_material_escrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='descricao',
            field=models.TextField(max_length=100),
        ),
    ]
