# Generated by Django 5.1.4 on 2025-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0010_alter_aulas_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aulas',
            name='descricao',
            field=models.TextField(max_length=1000),
        ),
    ]
